### ISSUE TITLE
Input 1 gives NumberMustBeInRange exception

### ISSUE THREAD

**Issue by azzimccc** [fredonia88/tic_tac_toe#3]
Hi, so I download and tried the program and it seems that inputing 1 gives the NumberMustBeInRange exception even though the slot is available and 1 is greater than 0.
![image](https://user-images.githubusercontent.com/85424390/124402552-881c7800-dd63-11eb-87b2-127bace83549.png)

**Comment by fredonia88** [comment]
@azzimccc - thanks for catching this! I've fixed the bug.
